name: "tagged-release"

on:
  push:
    tags:
      - "*.*"

jobs:
  on-main-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1.2.9
        id: contains_tag
        with:
          reference: "master"
          tag: "${{ github.ref }}"
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: on-main-branch-check
    if: ${{ needs.on-main-branch-check.outputs.on_main == 'true' }}
    steps:

      # --- from workflow.yml ---
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Validation
        uses: gradle/wrapper-validation-action@v1

      - name: JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle
            .gradle/loom-cache
          key: caches-${{ hashFiles('~/.gradle', '.gradle/loom-cache') }}
          restore-keys: |
            caches-

      - name: Build
        run: ./gradlew build
      # --- from workflow.yml ---

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/*.jar
